ok ok bootrapping is safer and still fairly clean

diff --git a/bin/ellah b/bin/ellah
--- a/bin/ellah
+++ b/bin/ellah
@@ -8,11 +8,11 @@
 
 # shellcheck source=../_bootstrap.bash
 source "${ELLAH_ROOT}/_bootstrap.bash" || {
-  echo 'ellah failed to bootsrap' >&2
+  echo 'failed to bootsrap' >&2
   exit 1
 }
 
-log debug 'bootstrapped'
+log info 'bootstrapped'
 exit 0
 
 cmd=$1; shift
