refactored core functions into individual files; reorganized the test folder into functions and modules; added coverage to all core-functions

diff --git a/bin/ellah b/bin/ellah
--- a/bin/ellah
+++ b/bin/ellah
@@ -7,9 +7,9 @@
 }
 
 # shellcheck source=../_bootstrap.bash
-source "${ELLAH_ROOT}/_bootstrap.bash" || {
-  echo 'failed to bootsrap' >&2
-  exit 1
+source "${ELLAH_ROOT}/core/bootstrap.bash" || {
+   echo 'failed to bootsrap' >&2
+   exit 1
 }
 
 log info 'bootstrapped'
